fpath+=("$(/home/linuxbrew/.linuxbrew/bin/brew --prefix)/share/zsh/site-functions")
eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

export PATH=${HOME}/.local/share/tmux/plugins/t-smart-tmux-session-manager/bin:${PATH}
export PATH=${HOME}/.local/bin:${PATH}
